version: "3"

services:
  dev:
    build: .
    volumes:
      - "../:/workspace/TrainingCode"
    working_dir: "/workspace/TrainingCode"
    tty: true
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp:unconfined"
